"""initial schema

Revision ID: 9e01ac85b7e0
Revises: 
Create Date: 2026-07-20 18:05:15.363516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e01ac85b7e0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('current_node', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_created_at'), 'pipeline_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_status'), 'pipeline_runs', ['status'], unique=False)
    op.create_table('titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('imdb_id', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('popularity', sa.Float(), nullable=False),
    sa.Column('genres', sa.JSON(), nullable=False),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('poster_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_titles_source_external')
    )
    op.create_index(op.f('ix_titles_imdb_id'), 'titles', ['imdb_id'], unique=False)
    op.create_index(op.f('ix_titles_source'), 'titles', ['source'], unique=False)
    op.create_index(op.f('ix_titles_title'), 'titles', ['title'], unique=False)
    op.create_index(op.f('ix_titles_tmdb_id'), 'titles', ['tmdb_id'], unique=False)
    op.create_index(op.f('ix_titles_type'), 'titles', ['type'], unique=False)
    op.create_table('ai_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('weaknesses', sa.JSON(), nullable=False),
    sa.Column('audience_reception', sa.Text(), nullable=True),
    sa.Column('notable_topics', sa.JSON(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_summaries_pipeline_run_id'), 'ai_summaries', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_ai_summaries_title_id'), 'ai_summaries', ['title_id'], unique=False)
    op.create_table('rankings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('components', sa.JSON(), nullable=False),
    sa.Column('weights_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rankings_pipeline_run_id'), 'rankings', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_rankings_position'), 'rankings', ['position'], unique=False)
    op.create_index(op.f('ix_rankings_score'), 'rankings', ['score'], unique=False)
    op.create_index(op.f('ix_rankings_title_id'), 'rankings', ['title_id'], unique=False)
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('critic_score', sa.Float(), nullable=True),
    sa.Column('audience_score', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ratings_source'), 'ratings', ['source'], unique=False)
    op.create_index(op.f('ix_ratings_title_id'), 'ratings', ['title_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_source'), 'reviews', ['source'], unique=False)
    op.create_index(op.f('ix_reviews_title_id'), 'reviews', ['title_id'], unique=False)
    op.create_table('scripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=True),
    sa.Column('title_id', sa.Integer(), nullable=True),
    sa.Column('hook', sa.Text(), nullable=True),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('ranked_list', sa.JSON(), nullable=False),
    sa.Column('cta', sa.Text(), nullable=True),
    sa.Column('video_title', sa.String(length=255), nullable=True),
    sa.Column('thumbnail_text', sa.String(length=255), nullable=True),
    sa.Column('hashtags', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scripts_pipeline_run_id'), 'scripts', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_scripts_title_id'), 'scripts', ['title_id'], unique=False)
    op.create_table('sentiment_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=16), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentiment_results_content_id'), 'sentiment_results', ['content_id'], unique=False)
    op.create_index(op.f('ix_sentiment_results_content_type'), 'sentiment_results', ['content_type'], unique=False)
    op.create_index(op.f('ix_sentiment_results_label'), 'sentiment_results', ['label'], unique=False)
    op.create_index(op.f('ix_sentiment_results_title_id'), 'sentiment_results', ['title_id'], unique=False)
    op.create_table('social_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('platform_id', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('engagement', sa.JSON(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'platform_id', name='uq_social_source_platform')
    )
    op.create_index(op.f('ix_social_posts_source'), 'social_posts', ['source'], unique=False)
    op.create_index(op.f('ix_social_posts_title_id'), 'social_posts', ['title_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_posts_title_id'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_source'), table_name='social_posts')
    op.drop_table('social_posts')
    op.drop_index(op.f('ix_sentiment_results_title_id'), table_name='sentiment_results')
    op.drop_index(op.f('ix_sentiment_results_label'), table_name='sentiment_results')
    op.drop_index(op.f('ix_sentiment_results_content_type'), table_name='sentiment_results')
    op.drop_index(op.f('ix_sentiment_results_content_id'), table_name='sentiment_results')
    op.drop_table('sentiment_results')
    op.drop_index(op.f('ix_scripts_title_id'), table_name='scripts')
    op.drop_index(op.f('ix_scripts_pipeline_run_id'), table_name='scripts')
    op.drop_table('scripts')
    op.drop_index(op.f('ix_reviews_title_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_source'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_ratings_title_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_source'), table_name='ratings')
    op.drop_table('ratings')
    op.drop_index(op.f('ix_rankings_title_id'), table_name='rankings')
    op.drop_index(op.f('ix_rankings_score'), table_name='rankings')
    op.drop_index(op.f('ix_rankings_position'), table_name='rankings')
    op.drop_index(op.f('ix_rankings_pipeline_run_id'), table_name='rankings')
    op.drop_table('rankings')
    op.drop_index(op.f('ix_ai_summaries_title_id'), table_name='ai_summaries')
    op.drop_index(op.f('ix_ai_summaries_pipeline_run_id'), table_name='ai_summaries')
    op.drop_table('ai_summaries')
    op.drop_index(op.f('ix_titles_type'), table_name='titles')
    op.drop_index(op.f('ix_titles_tmdb_id'), table_name='titles')
    op.drop_index(op.f('ix_titles_title'), table_name='titles')
    op.drop_index(op.f('ix_titles_source'), table_name='titles')
    op.drop_index(op.f('ix_titles_imdb_id'), table_name='titles')
    op.drop_table('titles')
    op.drop_index(op.f('ix_pipeline_runs_status'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_created_at'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    # ### end Alembic commands ###
